ent = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor ' ,type(ent))
print('É um alfanumérico? ', ent.isalnum())
print('É alfabético? ', ent.isalpha())
print('É um decimal? ', ent.isdecimal())
print('É um dígito?', ent.isdigit())
print('É um identificador? ', ent.isidentifier())
print('Está escrito em letras minúsculas ? ', ent.islower())
print('É um número? ', ent.isnumeric())
print('É uma string não vazia? ', ent.isprintable())
print('Só tem espaço? ', ent.isspace())
print('Está capitalizada? ', ent.istitle())
print('Está escrito em letras maiúsculas? ', ent.isupper())

