ent = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor {}'.format(type(ent)))
print('É um alfanumérico? {}'.format(ent.isalnum()))
print('É alfabético? {}'.format(ent.isalpha()))
print('É um decimal? {}'.format(ent.isdecimal()))
print('É um dígito? {}'.format(ent.isdigit()))
print('É um identificador? {}'.format(ent.isidentifier()))
print('Está escrito em letras minúsculas ? {}'.format(ent.islower()))
print('É um número? {} '.format(ent.isnumeric()))
print('É uma string não vazia? {}'.format(ent.isprintable()))
print('Só tem espaço? {}'.format(ent.isspace()))
print('Está capitalizada? {}'.format(ent.istitle()))
print('Está escrito em letras maiúsculas? {}'.format(ent.isupper()))